"""Add full_name, created_at, updated_at to users table and modify email type.

Revision ID: 000000000001
Revises: 
Create Date: 2025-07-04 01:00:00.000000 # Example, actual date will vary

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000001' # This is a placeholder ID. You can replace it with a short unique hash if you prefer.
down_revision = None # This is the first revision, so no previous revision.
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add full_name column
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        
        # Add created_at column
        # Use server_default to set existing rows' created_at
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
        
        # Add updated_at column
        # For updated_at, set a default and a trigger (trigger is external to Alembic, often handled by ORM or manual SQL setup)
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
        
        # Alter email column type from TEXT to String(255)
        # This is done using batch_alter_table for safety in older versions of SQLAlchemy
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('full_name')
    # ### end Alembic commands ###